[INFO   ] Logger: Record log in C:\Users\vicoppliger\.kivy\logs\kivy_20-09-01_35.txt
[INFO   ] deps: Successfully imported "kivy_deps.angle" 0.2.0
[INFO   ] deps: Successfully imported "kivy_deps.glew" 0.2.0
[INFO   ] deps: Successfully imported "kivy_deps.sdl2" 0.2.0
[INFO   ] Kivy: v2.0.0rc3, git-20c14b2, 20200615
[INFO   ] Kivy: Installed at "C:\Users\vicoppliger\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\__init__.py"
[INFO   ] Python: v3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:43:08) [MSC v.1926 32 bit (Intel)]
[INFO   ] Python: Interpreter at "C:\Users\vicoppliger\AppData\Local\Programs\Python\Python38-32\python.exe"
[WARNING] stderr: Process Skeleton Generator Worker:
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "C:\Users\vicoppliger\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 315, in _bootstrap
[WARNING] stderr:     self.run()
[WARNING] stderr:   File "C:\Users\vicoppliger\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 108, in run
[WARNING] stderr:     self._target(*self._args, **self._kwargs)
[WARNING] stderr:   File "C:\Users\vicoppliger\AppData\Local\JetBrains\PyCharm Community Edition 2020.2\plugins\python-ce\helpers\generator3\util_methods.py", line 872, in _multiprocessing_wrapper
[WARNING] stderr:     data.result_conn.send(func(*args, **kwargs))
[WARNING] stderr:   File "C:\Users\vicoppliger\AppData\Local\JetBrains\PyCharm Community Edition 2020.2\plugins\python-ce\helpers\generator3\core.py", line 617, in generate_skeleton
[WARNING] stderr:     __import__(name)  # sys.modules will fill up with what we want
[WARNING] stderr:   File "C:\Users\vicoppliger\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\lib\gstplayer\__init__.py", line 26, in <module>
[WARNING] stderr:     from kivy.lib.gstplayer._gstplayer import (
[WARNING] stderr: ImportError: DLL load failed while importing _gstplayer: Le module spécifié est introuvable.
